<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ApiScannerLogger</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuciAPI.Middleware" Version="1.5.3" />
    <PackageReference Include="NuciLog" Version="1.2.0" />
    <PackageReference Include="NuciLog.Core" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
